### ISSUE TITLE
GREP_OPTIONS is deprecated on Ubuntu 16.04 installation

### ISSUE THREAD

**Issue by taddeimania** [mattjmorrison/dotfiles#48]
Apparently GREP_OPTIONS is being deprecated and throwing like 3 errors when running any command inside of a git reposity.

Problematic line:
https://github.com/JarrodCTaylor/dotfiles/blob/master/zsh/zshrc#L110

Not sure if this is the "right" thing to do, but I found this temporary hack somewhere on the internet. I had to change the path to where my grep was (the example online said to put it in /usr/bin/grep which didn't work for me.

```
alias grep="/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS
```

**Comment by mattjmorrison** [comment]
@taddeimania new ownership bro, go pound sand
